In [ ]:

#Problem 10

In [ ]:
"""

In this problem, generate 20 data points, each containing 8 features. Use Gaussian
distribution with 0 mean and 0.1 variance. Use PCA to reduce the 8 features, for every data point, into
1, 2, and 3 features. Explain how the PCA matrix is constructed for each case. Use only Numpy.
"""

'\n\nIn this problem, generate 20 data points, each containing 8 features. Use Gaussian\ndistribution with 0 mean and 0.1 variance. Use PCA to reduce the 8 features, for every data point, into\n1, 2, and 3 features. Explain how the PCA matrix is constructed for each case. Use only Numpy.\n'

In [ ]:
import numpy as np
np.random.seed(seed=1111)
# In this code, we show how to use PCA...
# Generate some dataset... 

number_of_data_points = 20
number_of_features_per_data_point = 8

# stack the data into some list
data = np.zeros(shape=(number_of_data_points,number_of_features_per_data_point))
for data_index in range(number_of_data_points):
  data_point = np.random.normal(loc = 0, scale=np.sqrt(.1), size=(number_of_features_per_data_point))
  print("datapoint {} = ".format(data_index),data_point)
  data[data_index,:] = data_point

datapoint 0 =  [-0.41109936 -0.33930893  0.24988293 -0.27773194  0.47491776 -0.00756716
  0.0872627  -0.30560033]
datapoint 1 =  [-0.49973938 -0.06440758 -0.4894153  -0.12380243  0.34607517 -0.11879691
 -0.29685384  0.13103896]
datapoint 2 =  [ 0.43054754  0.4360968   0.21090793  0.05437967  0.17622315  0.20701356
  0.07888606 -0.19821543]
datapoint 3 =  [ 0.1959256   0.1070823  -0.2846397  -0.25701818 -0.16764502  0.39749533
  0.12105425  0.09704596]
datapoint 4 =  [ 0.28729259 -0.25207392 -0.21518174  0.06670843 -0.12591516 -0.23277155
 -0.28967942 -0.15191694]
datapoint 5 =  [ 0.08592852 -0.62205697  0.40346436  0.23477395  0.35706632 -0.17155397
 -0.04041742 -0.33625674]
datapoint 6 =  [-0.28599726 -0.24328181 -0.17890868 -0.12875793  0.23699895  0.07925931
  0.3869816   0.14885412]
datapoint 7 =  [-0.07775584 -0.00198618 -0.27684164  0.85001411 -0.02739521 -0.00612189
 -0.00455989 -0.20450686]
datapoint 8 =  [-0.74816952  0.0438504   0.22125228 -0.23477281  0.50358981  0.26055657


In [ ]:
# Next, we calculate the vector mean of the data: 

X_bar = np.mean(data,axis=0)
print("X bar = ", X_bar)
print("X bar is of size {}, which is equal to the number of features for each data point, {}".format((X_bar.shape),number_of_features_per_data_point))

X bar =  [ 0.0017266  -0.03602891  0.03257338 -0.02029355  0.09753193 -0.00611239
  0.01038265 -0.04300285]
X bar is of size (8,), which is equal to the number of features for each data point, 8


In [ ]:
# Next, we compute the covariance matrix of the data. The covariance matrix is of size NXN
print("The covariance of the data is size {} X {}.".format(number_of_data_points,number_of_data_points))
# For each row in the data matrix, we subtract the datapoint vector with the mean vector X_bar and save it in a data matrix

data_matrix_minus_mean = np.zeros(shape=(number_of_data_points,number_of_features_per_data_point))
for data_index in range(number_of_data_points):
  data_matrix_minus_mean[data_index,:] = data[data_index,:] - X_bar
print(data_matrix_minus_mean)

The covariance of the data is size 20 X 20.
[[-4.12825959e-01 -3.03280013e-01  2.17309546e-01 -2.57438387e-01
   3.77385824e-01 -1.45476885e-03  7.68800504e-02 -2.62597474e-01]
 [-5.01465982e-01 -2.83786644e-02 -5.21988682e-01 -1.03508877e-01
   2.48543237e-01 -1.12684518e-01 -3.07236482e-01  1.74041809e-01]
 [ 4.28820937e-01  4.72125717e-01  1.78334547e-01  7.46732197e-02
   7.86912185e-02  2.13125949e-01  6.85034115e-02 -1.55212579e-01]
 [ 1.94198999e-01  1.43111216e-01 -3.17213078e-01 -2.36724629e-01
  -2.65176957e-01  4.03607722e-01  1.10671602e-01  1.40048811e-01]
 [ 2.85565984e-01 -2.16045011e-01 -2.47755121e-01  8.70019785e-02
  -2.23447095e-01 -2.26659159e-01 -3.00062070e-01 -1.08914088e-01]
 [ 8.42019163e-02 -5.86028057e-01  3.70890979e-01  2.55067495e-01
   2.59534387e-01 -1.65441583e-01 -5.08000646e-02 -2.93253889e-01]
 [-2.87723862e-01 -2.07252892e-01 -2.11482059e-01 -1.08464384e-01
   1.39467015e-01  8.53717008e-02  3.76598956e-01  1.91856976e-01]
 [-7.94824420e-02  3.4042

In [ ]:
# Now, for each vector in data_matrix_minus_mean, we compute the outer product matrix 
matricies_list = []
for data_index in range(number_of_data_points):
  outer_product_matrix = np.outer(data_matrix_minus_mean[data_index,:],data_matrix_minus_mean[data_index,:])
  matricies_list.append(outer_product_matrix)

Covariance_matrix = np.array ( (1/number_of_data_points) * sum(matricies_list) )

print((Covariance_matrix))

[[ 0.11730023  0.03551099  0.00200871  0.01966661 -0.07528854 -0.01098487
   0.00323347 -0.00155793]
 [ 0.03551099  0.10188513 -0.00211975  0.01350572 -0.03594617  0.00797219
   0.00025654 -0.00392955]
 [ 0.00200871 -0.00211975  0.12529856 -0.01457684  0.01875294 -0.00600595
   0.02920082 -0.01315025]
 [ 0.01966661  0.01350572 -0.01457684  0.08226767 -0.00932793  0.00918602
  -0.01738103 -0.01509612]
 [-0.07528854 -0.03594617  0.01875294 -0.00932793  0.08893539  0.00783145
  -0.00147974  0.00017013]
 [-0.01098487  0.00797219 -0.00600595  0.00918602  0.00783145  0.05387119
  -0.01811303 -0.00860395]
 [ 0.00323347  0.00025654  0.02920082 -0.01738103 -0.00147974 -0.01811303
   0.09831804  0.02703366]
 [-0.00155793 -0.00392955 -0.01315025 -0.01509612  0.00017013 -0.00860395
   0.02703366  0.04535868]]


One feature:

In [ ]:
# Next, we get the highest eigenvalues and eigenvectors to construct the PCA weights matrix

number_of_reduced_features = 1

eig_values_1, eig_vectors_1 = np.linalg.eig(Covariance_matrix)
print("eig_values = ", eig_values_1)
print("eig_vectors = ", eig_vectors_1)

eig_values =  [0.21180384 0.15350738 0.10837635 0.02059126 0.02861757 0.04267438
 0.08003516 0.06762894]
eig_vectors =  [[-0.65199185 -0.205451    0.00578758 -0.50872115  0.32812505  0.15702513
  -0.37513816 -0.02853486]
 [-0.42371555 -0.05572272  0.20915604 -0.06667133  0.07338802 -0.26100978
   0.82489389 -0.12331651]
 [ 0.16409169 -0.69739918  0.61978997  0.25761218  0.13225356  0.00979331
  -0.11804913 -0.06842623]
 [-0.21074453  0.25878414  0.33456232  0.18981134  0.07163307 -0.09897006
  -0.0710373   0.84893142]
 [ 0.56561485  0.06867303  0.15756365 -0.64534569  0.41070711 -0.11954995
   0.15350068  0.16592626]
 [ 0.02610118  0.20530074  0.25047229 -0.00136165  0.01661383  0.91242881
   0.24656474 -0.02890657]
 [ 0.05049494 -0.58534644 -0.42455404 -0.19332843 -0.3360088   0.20196807
   0.24304031  0.47374697]
 [ 0.02968589 -0.10888148 -0.43856574  0.4248724   0.76319564  0.0985718
   0.12811841  0.07621547]]


In [ ]:
# Given the above eigen values and vector, we get the following W_PCA matrix

W_PCA_1 = np.zeros(shape=(number_of_reduced_features, number_of_features_per_data_point))

# we pick the highest two values and their corresponding eigrn values
W_PCA_1[0,:] = eig_vectors_1[0,:]

print("The PCA matrix = \n", W_PCA_1)

The PCA matrix = 
 [[-0.65199185 -0.205451    0.00578758 -0.50872115  0.32812505  0.15702513
  -0.37513816 -0.02853486]]


In [ ]:
# Next, for each data point, we get the reduced vector z...

reduced_data = np.zeros(shape=(number_of_data_points,1))

for data_index in range(number_of_data_points):
  reduced_data[data_index,:] = np.matmul(W_PCA_1, data[data_index,:])

print("The reduced matrix = ", reduced_data)

The reduced matrix =  [[ 6.11107988e-01]
 [ 6.01730844e-01]
 [-3.30361011e-01]
 [-6.14118899e-02]
 [-1.35567122e-01]
 [ 6.96594161e-02]
 [ 2.41708706e-01]
 [-3.85322341e-01]
 [ 8.85273676e-01]
 [ 5.63946302e-01]
 [ 1.88202751e-01]
 [-1.69388487e-01]
 [-1.78554341e-01]
 [ 1.78457263e-01]
 [-2.25915970e-01]
 [-2.29003113e-01]
 [-6.60633441e-01]
 [-3.06138040e-04]
 [ 4.59944246e-01]
 [-5.20292337e-01]]


Two features:

In [ ]:
# Next, we get the highest eigenvalues and eigenvectors to construct the PCA weights matrix

number_of_reduced_features = 2

eig_values_2, eig_vectors_2 = np.linalg.eig(Covariance_matrix)
print("eig_values = ", eig_values_2)
print("eig_vectors = ", eig_vectors_2)

eig_values =  [0.21180384 0.15350738 0.10837635 0.02059126 0.02861757 0.04267438
 0.08003516 0.06762894]
eig_vectors =  [[-0.65199185 -0.205451    0.00578758 -0.50872115  0.32812505  0.15702513
  -0.37513816 -0.02853486]
 [-0.42371555 -0.05572272  0.20915604 -0.06667133  0.07338802 -0.26100978
   0.82489389 -0.12331651]
 [ 0.16409169 -0.69739918  0.61978997  0.25761218  0.13225356  0.00979331
  -0.11804913 -0.06842623]
 [-0.21074453  0.25878414  0.33456232  0.18981134  0.07163307 -0.09897006
  -0.0710373   0.84893142]
 [ 0.56561485  0.06867303  0.15756365 -0.64534569  0.41070711 -0.11954995
   0.15350068  0.16592626]
 [ 0.02610118  0.20530074  0.25047229 -0.00136165  0.01661383  0.91242881
   0.24656474 -0.02890657]
 [ 0.05049494 -0.58534644 -0.42455404 -0.19332843 -0.3360088   0.20196807
   0.24304031  0.47374697]
 [ 0.02968589 -0.10888148 -0.43856574  0.4248724   0.76319564  0.0985718
   0.12811841  0.07621547]]


In [ ]:
# Given the above eigen values and vector, we get the following W_PCA matrix

W_PCA_2 = np.zeros(shape=(number_of_reduced_features, number_of_features_per_data_point))

# we pick the highest two values and their corresponding eigrn values
W_PCA_2[0,:] = eig_vectors_2[0,:]
W_PCA_2[1,:] = eig_vectors_2[1,:]

print("The PCA matrix = \n", W_PCA_2)

The PCA matrix = 
 [[-0.65199185 -0.205451    0.00578758 -0.50872115  0.32812505  0.15702513
  -0.37513816 -0.02853486]
 [-0.42371555 -0.05572272  0.20915604 -0.06667133  0.07338802 -0.26100978
   0.82489389 -0.12331651]]


In [ ]:
# Next, for each data point, we get the reduced vector z...

reduced_data = np.zeros(shape=(number_of_data_points,2))

for data_index in range(number_of_data_points):
  reduced_data[data_index,:] = np.matmul(W_PCA_2, data[data_index,:])

print("The reduced matrix = ", reduced_data)

The reduced matrix =  [[ 6.11107988e-01  4.10374098e-01]
 [ 6.01730844e-01 -8.34010335e-02]
 [-3.30361011e-01 -1.17827117e-01]
 [-6.14118899e-02 -1.59545774e-01]
 [-1.35567122e-01 -3.25844126e-01]
 [ 6.96594161e-02  1.46095354e-01]
 [ 2.41708706e-01  4.03470459e-01]
 [-3.85322341e-01 -6.04725954e-02]
 [ 8.85273676e-01  1.77155571e-01]
 [ 5.63946302e-01  1.15984111e-01]
 [ 1.88202751e-01 -3.78795679e-01]
 [-1.69388487e-01 -7.86425203e-01]
 [-1.78554341e-01  4.10928214e-01]
 [ 1.78457263e-01  9.55710003e-02]
 [-2.25915970e-01  1.29093870e-01]
 [-2.29003113e-01 -4.20622143e-01]
 [-6.60633441e-01  3.89802933e-01]
 [-3.06138040e-04 -1.69537254e-01]
 [ 4.59944246e-01  6.87138524e-01]
 [-5.20292337e-01  1.78108209e-01]]


Three features:

In [ ]:
# Next, we get the highest eigenvalues and eigenvectors to construct the PCA weights matrix

number_of_reduced_features = 3

eig_values_3, eig_vectors_3 = np.linalg.eig(Covariance_matrix)
print("eig_values = ", eig_values_3)
print("eig_vectors = ", eig_vectors_3)

eig_values =  [0.21180384 0.15350738 0.10837635 0.02059126 0.02861757 0.04267438
 0.08003516 0.06762894]
eig_vectors =  [[-0.65199185 -0.205451    0.00578758 -0.50872115  0.32812505  0.15702513
  -0.37513816 -0.02853486]
 [-0.42371555 -0.05572272  0.20915604 -0.06667133  0.07338802 -0.26100978
   0.82489389 -0.12331651]
 [ 0.16409169 -0.69739918  0.61978997  0.25761218  0.13225356  0.00979331
  -0.11804913 -0.06842623]
 [-0.21074453  0.25878414  0.33456232  0.18981134  0.07163307 -0.09897006
  -0.0710373   0.84893142]
 [ 0.56561485  0.06867303  0.15756365 -0.64534569  0.41070711 -0.11954995
   0.15350068  0.16592626]
 [ 0.02610118  0.20530074  0.25047229 -0.00136165  0.01661383  0.91242881
   0.24656474 -0.02890657]
 [ 0.05049494 -0.58534644 -0.42455404 -0.19332843 -0.3360088   0.20196807
   0.24304031  0.47374697]
 [ 0.02968589 -0.10888148 -0.43856574  0.4248724   0.76319564  0.0985718
   0.12811841  0.07621547]]


In [ ]:
# Given the above eigen values and vector, we get the following W_PCA matrix

W_PCA_3 = np.zeros(shape=(number_of_reduced_features, number_of_features_per_data_point))

# we pick the highest two values and their corresponding eigrn values
W_PCA_3[0,:] = eig_vectors_3[0,:]
W_PCA_3[1,:] = eig_vectors_3[1,:]
W_PCA_3[2,:] = eig_vectors_3[2,:]

print("The PCA matrix = \n", W_PCA_3)

The PCA matrix = 
 [[-0.65199185 -0.205451    0.00578758 -0.50872115  0.32812505  0.15702513
  -0.37513816 -0.02853486]
 [-0.42371555 -0.05572272  0.20915604 -0.06667133  0.07338802 -0.26100978
   0.82489389 -0.12331651]
 [ 0.16409169 -0.69739918  0.61978997  0.25761218  0.13225356  0.00979331
  -0.11804913 -0.06842623]]


In [ ]:
# Next, for each data point, we get the reduced vector z...

reduced_data = np.zeros(shape=(number_of_data_points,3))

for data_index in range(number_of_data_points):
  reduced_data[data_index,:] = np.matmul(W_PCA_3, data[data_index,:])

print("The reduced matrix = ", reduced_data)

The reduced matrix =  [[ 6.11107988e-01  4.10374098e-01  3.25848830e-01]
 [ 6.01730844e-01 -8.34010335e-02 -3.01629902e-01]
 [-3.30361011e-01 -1.17827117e-01 -5.91726102e-02]
 [-6.14118899e-02 -1.59545774e-01 -3.24366883e-01]
 [-1.35567122e-01 -3.25844126e-01  1.32415071e-01]
 [ 6.96594161e-02  1.46095354e-01  8.31789201e-01]
 [ 2.41708706e-01  4.03470459e-01 -4.50688607e-02]
 [-3.85322341e-01 -6.04725954e-02  4.68652427e-02]
 [ 8.85273676e-01  1.77155571e-01  1.96699301e-02]
 [ 5.63946302e-01  1.15984111e-01  1.51783842e-01]
 [ 1.88202751e-01 -3.78795679e-01  3.21544701e-01]
 [-1.69388487e-01 -7.86425203e-01 -1.37813070e-01]
 [-1.78554341e-01  4.10928214e-01  2.83768552e-01]
 [ 1.78457263e-01  9.55710003e-02  8.42674826e-02]
 [-2.25915970e-01  1.29093870e-01 -3.31419331e-01]
 [-2.29003113e-01 -4.20622143e-01  3.24969223e-01]
 [-6.60633441e-01  3.89802933e-01 -1.44333879e-01]
 [-3.06138040e-04 -1.69537254e-01 -5.34227897e-01]
 [ 4.59944246e-01  6.87138524e-01  5.27652374e-01]
 [-5.2029

each matrix is made by subtracting the mean vector from the datapoint in order to do the dimensionality reduction on the dataset but maintain as much information as possible. 

Removing average info to cut down in it's size, as thats where majority of data points will be.